### ISSUE TITLE
Apostrophes remaining in output string?

### ISSUE THREAD

**Issue by dhruvbhatia** [donbonifacio/clojure-slugifier#3]
Great library - are apostrophes `'` meant to remain in the slugified output string?

``` clojure
(clojure-slugifier.core/slugify "André Conceição's House")
=> "andre-conceicao's-house"
```

**Comment by donbonifacio** [comment]
No, they are not, I'll fix this.

**Comment by donbonifacio** [comment]
New version `0.3.0` available on clojars. Thanks @dhruvbhatia :)

**Comment by dhruvbhatia** [comment]
@donbonifacio Thanks for the quick fix! :+1:
